/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.os.telas;

import br.com.os.dal.ModuloConexao;
import java.text.DateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import java.sql.*;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author bruno.alves
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Connection conexao = null;

    /**
     * Creates new form TelePrincipal
     */
    public TelaPrincipal() {
        initComponents();
        conexao = ModuloConexao.conector();
    }
    //  Função para  gerar relatorio de todos os cliente  via Ireport.
    private void relatorioCliente() {
        int Confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão desse relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (Confirma == JOptionPane.YES_OPTION) {
            //imprimindo relatorio com o framework jasperreport

            try {
                // usando o jasperprint
                //usando a classe para  preparar a impressão do relatorio
                JasperPrint print = JasperFillManager.fillReport("C:\\Users\\bruno.alves\\Documents\\NetBeansProjects\\projeto_sistema_os\\src\\Relatorios\\clientes.jasper", null, conexao);

                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }

    }
    //Função para gerar relatorio de todas as OS Abertas no sistemas.
    private void relatorioServico() {
        int Confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão desse relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (Confirma == JOptionPane.YES_OPTION) {
            //imprimindo relatorio com o framework jasperreport

            try {
                // usando o jasperprint
                //usando a classe para  preparar a impressão do relatorio
                JasperPrint print = JasperFillManager.fillReport("C:\\Users\\bruno.alves\\Documents\\NetBeansProjects\\projeto_sistema_os\\src\\Relatorios\\OS.jasper", null, conexao);

                JasperViewer.viewReport(print, false);
            } catch (JRException e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lbldata = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        menCadCliente = new javax.swing.JMenuItem();
        mencados = new javax.swing.JMenuItem();
        mencadusu = new javax.swing.JMenuItem();
        menRelServicos = new javax.swing.JMenu();
        menRelatorioServico = new javax.swing.JMenuItem();
        menRelatorioClientes = new javax.swing.JMenuItem();
        menAjuda = new javax.swing.JMenu();
        menAjudaSobre = new javax.swing.JMenuItem();
        mensair = new javax.swing.JMenu();
        menSairSair = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema para Asistêcia Técnica");
        setPreferredSize(new java.awt.Dimension(1024, 900));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/os/icones/logo_.png"))); // NOI18N

        lblusuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblusuario.setText("Usuário :");

        lbldata.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbldata.setText("Data :");

        menCad.setText("Cadastro");
        menCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadActionPerformed(evt);
            }
        });

        menCadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menCadCliente.setText("Cliente");
        menCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadClienteActionPerformed(evt);
            }
        });
        menCad.add(menCadCliente);

        mencados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        mencados.setText("OS");
        mencados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencadosActionPerformed(evt);
            }
        });
        menCad.add(mencados);

        mencadusu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mencadusu.setText("Usuários");
        mencadusu.setEnabled(false);
        mencadusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencadusuActionPerformed(evt);
            }
        });
        menCad.add(mencadusu);

        menu.add(menCad);

        menRelServicos.setText("Relátorios");
        menRelServicos.setEnabled(false);
        menRelServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelServicosActionPerformed(evt);
            }
        });

        menRelatorioServico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menRelatorioServico.setText("Serviços");
        menRelatorioServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelatorioServicoActionPerformed(evt);
            }
        });
        menRelServicos.add(menRelatorioServico);

        menRelatorioClientes.setText("Clientes");
        menRelatorioClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelatorioClientesActionPerformed(evt);
            }
        });
        menRelServicos.add(menRelatorioClientes);

        menu.add(menRelServicos);

        menAjuda.setText("Ajuda");

        menAjudaSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        menAjudaSobre.setText("Sobre");
        menAjudaSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menAjudaSobreMouseClicked(evt);
            }
        });
        menAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAjudaSobreActionPerformed(evt);
            }
        });
        menAjuda.add(menAjudaSobre);

        menu.add(menAjuda);

        mensair.setText("Sair");
        mensair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mensairMouseClicked(evt);
            }
        });
        mensair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensairActionPerformed(evt);
            }
        });

        menSairSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menSairSair.setText("Sair");
        mensair.add(menSairSair);

        menu.add(mensair);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lbldata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblusuario))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbldata)
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        setSize(new java.awt.Dimension(1168, 676));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mensairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensairActionPerformed
        //fecha a aplicação 
        this.dispose();
    }//GEN-LAST:event_mensairActionPerformed

    private void mensairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mensairMouseClicked
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair do sistema ?", "Sair:", JOptionPane.YES_NO_OPTION);
        if (resposta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_mensairMouseClicked

    private void menRelatorioServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelatorioServicoActionPerformed
       relatorioServico();
    }//GEN-LAST:event_menRelatorioServicoActionPerformed

    private void menAjudaSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menAjudaSobreMouseClicked
        Ajuda tela = new Ajuda();
        tela.setVisible(true);
    }//GEN-LAST:event_menAjudaSobreMouseClicked

    private void menAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAjudaSobreActionPerformed
        // TODO add your handling code here:
        Ajuda tela = new Ajuda();
        tela.setVisible(true);
    }//GEN-LAST:event_menAjudaSobreActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //as linhas a baixo substituem a label data lbldata pela data virtual do sistemas 
        //ao iniciar o form
        Date data = new Date();
        //formata a data em modelos que agente estipular.
        DateFormat formato = DateFormat.getDateInstance(DateFormat.SHORT);
        lbldata.setText(formato.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void menCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadClienteActionPerformed
        Cliente cliente = new Cliente();
        cliente.setVisible(true);
        desktop.add(cliente);
    }//GEN-LAST:event_menCadClienteActionPerformed

    private void mencadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencadosActionPerformed
        Os os = new Os();
        os.setVisible(true);
        desktop.add(os);
    }//GEN-LAST:event_mencadosActionPerformed

    private void mencadusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencadusuActionPerformed
        Usuario usuario = new Usuario();
        usuario.setVisible(true);
        desktop.add(usuario);
    }//GEN-LAST:event_mencadusuActionPerformed

    private void menCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCadActionPerformed

    private void menRelatorioClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelatorioClientesActionPerformed

        relatorioCliente();

    }//GEN-LAST:event_menRelatorioClientesActionPerformed

    private void menRelServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelServicosActionPerformed
        relatorioServico();
    }//GEN-LAST:event_menRelServicosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lbldata;
    public static javax.swing.JLabel lblusuario;
    private javax.swing.JMenu menAjuda;
    private javax.swing.JMenuItem menAjudaSobre;
    public static javax.swing.JMenu menCad;
    private javax.swing.JMenuItem menCadCliente;
    public static javax.swing.JMenu menRelServicos;
    private javax.swing.JMenuItem menRelatorioClientes;
    private javax.swing.JMenuItem menRelatorioServico;
    private javax.swing.JMenuItem menSairSair;
    private javax.swing.JMenuItem mencados;
    public static javax.swing.JMenuItem mencadusu;
    private javax.swing.JMenu mensair;
    private javax.swing.JMenuBar menu;
    // End of variables declaration//GEN-END:variables
}
